### ISSUE TITLE
input X should be diagonal matrix equal to A[0]

### ISSUE THREAD

**Issue by afshinrahimi** [tkipf/relational-gcn#2]
Hi,

I enjoyed reading the paper and the code. Good work!

In line 73 of train.py X = sp.csr_matrix(A[0].shape) shouldn't the diagonal be set to 1?
I think currently X is a zero matrix.

**Comment by tkipf** [comment]
Thanks for catching that! In principle, yes, absolutely! In this implementation, however, we use the `featureless=True` flag for the first layer, which implicitly replaces the input feature matrix with an identity matrix. It's a bit misleading that we still pass an (empty) feature matrix as dummy variable to the model. I will add a comment in the train file.
